# This workflow will build and push docker image to registery

name: Docker Build And Push

#on:
#  push:
#    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build and Push docker image
      with:
        image: ssdocker1510/pydemo
        tags: latest
        dockerfile: docker/Dockerfile
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Run Docker image
      run: |
        docker run -i ssdocker1510/pydemo:latest

#    - name: Docker Image Build And Push
#      env:
#        DOCKER_USERNAME: ${{ secret.DOCKER_USERNAME }}
#        DOCKER_PASSWORD: ${{ secret.DOCKER_PASSWORD }}    
#      run: |
#        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#        docker build -t pydemo:v0.1 -f docker/Dockerfile .
#        docker push pydemo:v0.1