# This workflow will build and push docker image to registery

name: Docker Build And Push

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Docker Image Build And Push
      env:
        DOCKER_USERNAME: ${{ secret.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secret.DOCKER_PASSWORD }}    
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker build -t pydemo:v0.1 -f docker/Dockerfile .
        docker push pydemo:v0.1