name: Python PyTest

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      run: |
        docker build -t pydemo:v0.1 -f docker/Dockerfile .
    - name: Push Docker Image
    - env:
        DOCKER_USERNAME: ${{secret.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secret.DOCKER_PASSWORD}}
    - run: | 
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push pydemo:v0.1